upstream bookstore { server bookstore:8000; }
upstream warehouse { server warehouse:8001; }
server {
    listen 80;
    client_max_body_size 10m;
    location /warehouse/ { rewrite ^/warehouse/(.*)$ /$1 break; proxy_pass http://warehouse; proxy_set_header Host $host; proxy_set_header X-Forwarded-Proto $scheme; }
    location /static/bookstore/ { alias /static/bookstore/; }
    location /static/warehouse/ { alias /static/warehouse/; }
    location / { proxy_pass http://bookstore; proxy_set_header Host $host; proxy_set_header X-Forwarded-Proto $scheme; }
}
