# Generated by Django 6.0.6 on 2026-07-26 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_order_orderitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"verbose_name": "Book", "verbose_name_plural": "Books"},
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=150, verbose_name="Author"),
        ),
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="catalog.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Price"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="stock",
            field=models.PositiveIntegerField(default=0, verbose_name="Stock"),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Title"),
        ),
    ]
