# Generated by Django 6.0.6 on 2026-08-03 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_book_options_alter_book_author_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "permissions": [
                    ("can_manage_books", "Can create, update and delete books")
                ],
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
            },
        ),
    ]
